### ISSUE TITLE
make menu works

### ISSUE THREAD

**Issue by daniloab** [SamuelPires1999/reviewer#34]
- [x] make menu items work
- [x] https://github.com/SamuelPires1999/reviewer/issues/28
![Screen Shot 2022-10-03 at 17 20 59](https://user-images.githubusercontent.com/19939822/193673408-92716d35-278f-4d09-96e7-89bca86f867b.png)

**Comment by SamuelPires1999** [comment]
Done!

**Comment by daniloab** [comment]
related the issue with the pr
